@expected_output:"ciao mondo!"
#module1
[
	basic
	other
	null
]

@template:true
@log:true
@stderr:true
@function:gabibbo
@"proto:int	ciaone(int)"
#module2
[
	basic
	a1
	a2
	a3
	aaaa
	testing
]

@function:ft_printf("ciao")
@"proto:int	ft_printf(int, ...)"

#ft_printf
[
	a
	b
	c
]
