/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   child_output.c                                     :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: alerusso <alessandro.russo.frc@gmail.co    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2026/06/27 15:41:53 by alerusso          #+#    #+#             */
/*   Updated: 2026/06/28 00:58:20 by alerusso         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "libunit.h"

/**
 * @brief open the expected output file, store its fd in a struct,
 * 			returns that struct
 * 
 * @param output_path path to that file
 * @return the struct with all the fds info
 */
t_test_fds	child_init(char *output_path)
{
	t_test_fds	fds;

	fds = (t_test_fds){0};
	fds.output = open(output_path, O_RDONLY);
	if (fds.output < 0)
		error(NULL, "child_init: cannot open output_path");
	return (fds);
}

/**
 * @brief close open fds, sets those to zero
 * 
 * @param fds fd struct
 */
void	child_cleanup(t_test_fds *fds)
{
	if (!fds)
		return ;
	ft_close(&fds->output);
	ft_close(&fds->redirect_stderr[0]);
	ft_close(&fds->redirect_stdout[0]);
	ft_close(&fds->redirect_stderr[1]);
	ft_close(&fds->redirect_stdout[1]);
	ft_close(&fds->restore_stderr);
	ft_close(&fds->restore_stdout);
	*fds = (t_test_fds){0};		
}

/**
 * @brief 	redirects the output to a pipe, to be able to process it later
 * 			if fd is different by 1/2, error is called.
 * @details 1)	the original fd data is saved with dup in fds->restore
 * 			2)	the pipe fds are stored in a int[2] fds->redirect
 * 			3)	the original fd data is override with output pipe end ([1])
 * @param fds fd struct
 * @param fd_fileno STDOUT_FILENO or STDERR_FILENO 
 */
void	child_redirect(t_test_fds *fds, int fd_fileno)
{
	if (fd_fileno != 1 && fd_fileno != 2)
	{
		child_cleanup(fds);
		error(NULL, "child_redirect: error");
	}
	else if (fd_fileno == 1)
	{
		fds->restore_stdout = dup(STDOUT_FILENO);
		if (fds->restore_stdout < 0)
			return (child_redirect(fds, -1));
		if (pipe(fds->redirect_stdout) != 0)
			return (child_redirect(fds, -1));
		if (dup2(fds->redirect_stdout[1], STDOUT_FILENO) < 0)
			return (child_redirect(fds, -1));
	}
	else if (fd_fileno == 2)
	{
		fds->restore_stderr = dup(STDERR_FILENO);
		if (fds->restore_stderr < 0)
			return (child_redirect(fds, -1));
		if (pipe(fds->redirect_stderr) != 0)
			return (child_redirect(fds, -1));
		if (dup2(fds->redirect_stderr[1], STDERR_FILENO) < 0)
			return (child_redirect(fds, -1));
	}
}

/**
 * @brief 	release the output of the pipe, writes it and returns a heap
 * 			char * back. Original fd for STDOUT/STDERR is restored.
 * @details 1)	output pipe end ([1]) is closed, original fd is restored
 * 			2)	the size of the pipe of buffer is got from ioctl syscall
 * 			3)	all file content is read and saved in a heap ptr
 * 			4)	output is printed and then returned
 * @param fds fd struct
 * @param fd_fileno STDOUT_FILENO or STDERR_FILENO 
 */
char	*child_release(t_test_fds *fds, int fd_fileno)
{
	char	*output;
	int		fd_input;
	int		pipe_size;

	if (fd_fileno != 1 && fd_fileno != 2)
		return (child_cleanup(fds), error(NULL, "child_release: error"), NULL);
	else if (fd_fileno == 1)
	{
		ft_close(&fds->redirect_stdout[1]);
		fd_input = fds->redirect_stdout[0];
		dup2(fds->restore_stdout, STDOUT_FILENO);
	}
	else if (fd_fileno == 2)
	{
		ft_close(&fds->redirect_stderr[1]);
		fd_input = fds->redirect_stderr[0];
		dup2(fds->restore_stderr, STDERR_FILENO);
	}
	if (ioctl(fd_input, FIONREAD, &pipe_size) < 0 || pipe_size < 0)
		return (NULL);
	output = ft_readfile(fd_input, pipe_size);
	if (output)
		write(fd_fileno, output, strlen(output));
	return (output);
}

/**
 * @brief 	returns the result of the strcmp between the expected output
 * 			and the output generated by the program to test.
 * @details LIBUNIT_FLAGS_EXIST is there because of stderr: it's usually
 * 			more useful to know if something has been printed rather than
 * 			comparing the effective output.
 * @param fds fd struct
 * @param test_flags see the e_test_enum. if LIBUNIT_FLAGS_EXIST is set,
 * 						child_cmp returns 1 if an output exists, else 0.
 * @param fd_fileno STDOUT_FILENO or STDERR_FILENO 
 */
int	child_cmp(t_test_fds *fds, int test_flags, int fd_fileno)
{
	char	*output_real;
	char	*output_expected;
	char	output_exist_bool;
	int		cmp;

	output_real = child_release(fds, fd_fileno);
	output_exist_bool = output_real != NULL;
	if (test_flags & LIBUNIT_FLAGS_EXIST)
		return (free(output_real), output_exist_bool);
	output_expected = ft_readfile(fds->output, -1);
	if (fds->output > 0)
		lseek(fds->output, 0, SEEK_SET);
	if (!output_expected && !output_real)
		return (free(output_real), free(output_expected), 0);
	else if (output_expected && !output_real)
		return (free(output_expected), 1);
	else if (!output_expected && output_real)
		return (free(output_real), -1);
	cmp = strcmp(output_expected, output_real);
	return (free(output_real), free(output_expected), cmp);
}
